plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 160
